version: 1.0.{build}

image: Visual Studio 2017

environment:
  Coveralls_Key:
    secure: 8k+ZP0tz89b1tE7yKah3uwxdbfkvgwWHlRwxQwPTQxLgkuJ8NWy4dd6BXsQ6/0aW
  GitHub_Key:
    secure: wtrwAJK+i7Ar5L8TXeXOUtsxmVD+2wXu9u9bOf6GRfPP0Xn2V4yqTatLwaT7VWA6
  PSGallery_Key:
    secure: 1OaraGK9SJwOoGVdOHdM1DH5rvfL2AcDfvUFvrMxKYIkqJ0LIw3rwe4nUhxMgBfE

before_build:
  - ps: Write-Host "Build version :`  $env:APPVEYOR_BUILD_VERSION"
  - ps: Write-Host "Branch        :`  $env:APPVEYOR_REPO_BRANCH"
  - ps: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
  - ps: Install-Module InvokeBuild -Scope CurrentUser -AllowClobber -Force
  - ps: Import-Module InvokeBuild

build_script:
  - ps: Invoke-Build
